# Generated by Django 3.0.4 on 2021-03-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='n1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='number',
            name='n2',
            field=models.IntegerField(),
        ),
    ]
