# Generated by Django 3.1.7 on 2021-03-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_auto_20210312_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='primos',
            field=models.JSONField(default=''),
        ),
    ]
