# Generated by Django 3.1.7 on 2021-03-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_number_primos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='primos',
            field=models.JSONField(default=[]),
        ),
    ]
